update workflow

diff --git a/.github/workflows/apigee-configuration-deploy-dev.yaml b/.github/workflows/apigee-configuration-deploy-dev.yaml
--- a/.github/workflows/apigee-configuration-deploy-dev.yaml
+++ b/.github/workflows/apigee-configuration-deploy-dev.yaml
@@ -98,32 +98,20 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
-      - name: Output Deployment Info
+      # The committed changes may have deleted the targetserver folder, so we need to check whether it still exists
+      # If it does, then we proceed with the deployment
+      # If it does not, we undeploy the targetserver from all environments
+      - name: Check if targetserver folder exists
+        id: check_folder
         run: |
-          echo "Preparing to deploy Target Server ${{ matrix.name }} to $APIGEE_X_ORG from branch ${{ github.ref_name }}"
-
-      - name: Install yq
-        run: |
-          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
-          sudo chmod +x /usr/bin/yq
-
-      - name: Render template with environment variable substitution from .env 
-        uses: ./.github/actions/render-envvars
-        with:
-          template: "targetservers/${{ matrix.name }}/template.yaml"
-          envfile: "targetservers/${{ matrix.name }}/.env.$APP_ENV"
-          output: "targetservers/${{ matrix.name }}/output.yaml"
-
-      - name: Convert output to an Array for apigeecli import command
-        run: |
-          # Convert YAML to JSON using yq
-          yq -o=json '[.targetserver]' targetservers/${{ matrix.name }}/output.yaml > targetservers/${{ matrix.name }}/targetservers.json
-          echo "✅ JSON written to targetservers/${{ matrix.name }}/targetservers.json"
-
-      - name: Print result
-        run: |
-          cat targetservers/${{ matrix.name }}/targetservers.json
- 
+          if [ -d "targetservers/${{ matrix.name }}" ]; then
+            echo "Targetserver folder exists"
+            echo "exists=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "Folder does not exist"
+            echo "exists=false" >> "$GITHUB_OUTPUT"
+          fi
+          
       - name: Authenticate to Google Cloud
         id: auth
         uses: google-github-actions/auth@v2
@@ -136,12 +124,70 @@ jobs:
           unzip apigeecli_v2.13.0_Linux_x86_64.zip
           sudo mv apigeecli_v2.13.0_Linux_x86_64/apigeecli /usr/local/bin/
 
+      - name: Install yq
+        run: |
+          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
+          sudo chmod +x /usr/bin/yq
+
+      - name: Output Deployment Info
+        if: steps.check_folder.outputs.exists == 'true'
+        run: |
+          echo "Preparing to deploy Target Server ${{ matrix.name }} to $APIGEE_X_ORG from branch ${{ github.ref_name }}"
+
+      - name: Render template with environment variable substitution from .env 
+        if: steps.check_folder.outputs.exists == 'true'
+        uses: ./.github/actions/render-envvars
+        with:
+          template: "targetservers/${{ matrix.name }}/template.yaml"
+          envfile: "targetservers/${{ matrix.name }}/.env.$APP_ENV"
+          output: "targetservers/${{ matrix.name }}/output.yaml"
+
+      - name: Convert output to an Array for apigeecli import command
+        if: steps.check_folder.outputs.exists == 'true'
+        run: |
+          # Convert YAML to JSON using yq
+          yq -o=json '[.targetserver]' targetservers/${{ matrix.name }}/output.yaml > targetservers/${{ matrix.name }}/targetservers.json
+          echo "✅ JSON written to targetservers/${{ matrix.name }}/targetservers.json"
+
+      - name: Print result
+        if: steps.check_folder.outputs.exists == 'true'
+        run: |
+          cat targetservers/${{ matrix.name }}/targetservers.json
+ 
       - name: Deploy ApigeeX Target Server
+        if: steps.check_folder.outputs.exists == 'true'
         run: |
           for APIGEE_X_ENV in $APIGEE_X_ENVS; do 
             echo "Deploying to environment: $APIGEE_X_ENV"
             apigeecli targetservers import --default-token -o "$APIGEE_X_ORG" -e "$APIGEE_X_ENV" --file targetservers/${{ matrix.name }}/targetservers.json
           done
+
+
+
+      # The committed changes have deleted the sharedflow, so we undeploy the sharedflow from all environments          
+      - name: Remove Deleted TargetServers
+        if: steps.check_folder.outputs.exists == 'false'
+        run: |
+          set +e  # disable immediate exit on error
+          echo "TargetServer ${{ matrix.name }} does not exist. Undeploying from all Environments."
+          ENVS=$(apigeecli environments list --default-token -o "$APIGEE_X_ORG"  | jq -r '. | join(" ")')
+          for APIGEE_X_ENV in $ENVS; do
+            OUTPUT=$(apigeecli targetservers delete --default-token -o "$APIGEE_X_ORG" -e "$APIGEE_X_ENV" --name "${{ matrix.name }}")
+            STATUS=$?
+
+            if [ "$STATUS" -eq 0 ]; then
+              echo "✅ Success"
+            elif echo "$OUTPUT" | grep -q "is referenced by deployment"; then
+              echo "ℹ️ TargetServer is referenced by a proxy deployed to this environment, so ignoring delete"
+            elif echo "$OUTPUT" | grep -q "not found"; then
+              echo "ℹ️ TargetServer is not deployed to this environment, so ignoring delete"
+            else
+              echo "❌ Unexpected error"
+              exit $STATUS
+            fi
+          done
+
+
 
   deploy-kvms:
     name: Deploy Changed KVMs
@@ -163,30 +209,19 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
-      - name: Output Deployment Info
+      # The committed changes may have deleted the targetserver folder, so we need to check whether it still exists
+      # If it does, then we proceed with the deployment
+      # If it does not, we delete the KVM from all environments
+      - name: Check if KVM folder exists
+        id: check_folder
         run: |
-          echo "Preparing to deploy KVM ${{ matrix.name }} to $APIGEE_X_ORG from branch ${{ github.ref_name }}"
-
-      - name: Install yq
-        run: |
-          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
-          sudo chmod +x /usr/bin/yq
-
-      - name: Render template with environment variable substitution from .env 
-        uses: ./.github/actions/render-envvars
-        with:
-          template: "kvms/${{ matrix.name }}/template.yaml"
-          envfile: "kvms/${{ matrix.name }}/.env.$APP_ENV"
-          output: "kvms/${{ matrix.name }}/output.yaml"
-
-      - name: Convert output for apigeecli kvms entries import command
-        run: |
-          yq -o json '.keyValueEntries = .kvm.entries | del .kvm' kvms/${{ matrix.name }}/output.yaml > kvms/${{ matrix.name }}/kvm-entries.json
-          echo "✅ KVM entries written to kvms/${{ matrix.name }}/kvm-entries.json"
-
-      - name: Print result
-        run: |
-          cat kvms/${{ matrix.name }}/kvm-entries.json
+          if [ -d "kvms/${{ matrix.name }}" ]; then
+            echo "KVM folder exists"
+            echo "exists=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "Folder does not exist"
+            echo "exists=false" >> "$GITHUB_OUTPUT"
+          fi
 
       - name: Authenticate to Google Cloud
         id: auth
@@ -200,7 +235,37 @@ jobs:
           unzip apigeecli_v2.13.0_Linux_x86_64.zip
           sudo mv apigeecli_v2.13.0_Linux_x86_64/apigeecli /usr/local/bin/
 
+      - name: Install yq
+        run: |
+          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
+          sudo chmod +x /usr/bin/yq
+
+      - name: Output Deployment Info
+        if: steps.check_folder.outputs.exists == 'true'
+        run: |
+          echo "Preparing to deploy KVM ${{ matrix.name }} to $APIGEE_X_ORG from branch ${{ github.ref_name }}"
+
+      - name: Render template with environment variable substitution from .env 
+        if: steps.check_folder.outputs.exists == 'true'
+        uses: ./.github/actions/render-envvars
+        with:
+          template: "kvms/${{ matrix.name }}/template.yaml"
+          envfile: "kvms/${{ matrix.name }}/.env.$APP_ENV"
+          output: "kvms/${{ matrix.name }}/output.yaml"
+
+      - name: Convert output for apigeecli kvms entries import command
+        if: steps.check_folder.outputs.exists == 'true'
+        run: |
+          yq -o json '.keyValueEntries = .kvm.entries | del .kvm' kvms/${{ matrix.name }}/output.yaml > kvms/${{ matrix.name }}/kvm-entries.json
+          echo "✅ KVM entries written to kvms/${{ matrix.name }}/kvm-entries.json"
+
+      - name: Print result
+        if: steps.check_folder.outputs.exists == 'true'
+        run: |
+          cat kvms/${{ matrix.name }}/kvm-entries.json
+
       - name: Create ApigeeX KVM if it doesn't exist
+        if: steps.check_folder.outputs.exists == 'true'
         run: |
           set +e  # disable immediate exit on error
 
@@ -221,6 +286,7 @@ jobs:
           done
 
       - name: Import entries into KVM
+        if: steps.check_folder.outputs.exists == 'true'
         run: |
           set +e  # disable immediate exit on error
 
@@ -236,6 +302,30 @@ jobs:
             #   echo "ℹ️ Already exists, treating as success"
             else
               echo "❌ Unexpected error importing KVM entries into ${{ matrix.name }} in environment $APIGEE_X_ENV"
+              exit $STATUS
+            fi
+          done
+
+
+      # The committed changes have deleted the kvm, so we delete the kvm from all environments          
+      - name: Remove Deleted KVMs
+        if: steps.check_folder.outputs.exists == 'false'
+        run: |
+          set +e  # disable immediate exit on error
+          echo "KVM ${{ matrix.name }} does not exist. Undeploying from all Environments."
+          ENVS=$(apigeecli environments list --default-token -o "$APIGEE_X_ORG"  | jq -r '. | join(" ")')
+          for APIGEE_X_ENV in $ENVS; do
+            OUTPUT=$(apigeecli kvms delete --default-token -o "$APIGEE_X_ORG" -e "$APIGEE_X_ENV" --name "${{ matrix.name }}")
+            STATUS=$?
+
+            if [ "$STATUS" -eq 0 ]; then
+              echo "✅ Success"
+            elif echo "$OUTPUT" | grep -q "is referenced by deployment"; then
+              echo "ℹ️ KVM is referenced by a proxy deployed to this environment, so ignoring delete"
+            elif echo "$OUTPUT" | grep -q "not found"; then
+              echo "ℹ️ KVM is not deployed to this environment, so ignoring delete"
+            else
+              echo "❌ Unexpected error"
               exit $STATUS
             fi
           done
